[package]
name = "prime-time"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.64"
bytes = "1.2"
log = "0.4.17"
num-bigint = { version = "0.4.3", features = ["serde"] }
pretty_env_logger = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.85", features = ["arbitrary_precision"] }
tokio = { version = "1.21", features = ["full"] }
